version: '3.8'

services:
  app:
    image: ${PROJECT_NAME:-demo-project-1}:${IMAGE_TAG:-latest}
    container_name: ${PROJECT_NAME:-demo-project-1}
    restart: unless-stopped
    env_file: .env
    expose:
      - "80"
    networks:
      - infra_network

networks:
  # Kết nối vào chung network của Nginx trong folder infra
  infra_network:
    external: true
